version: '3.9'

services: 
  database:
    image: postgres
    container_name: app
    restart: always
    ports: 
      - 5433:5432
    environment: 
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_DB=app
    volumes:
      - pgdata:/data/postgres

volumes:
    pgdata:
     driver: local
